# Generated by Django 3.0.7 on 2020-06-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companyinfo.Tag', verbose_name='关键字'),
        ),
    ]
