# Generated by Django 3.0.7 on 2020-06-23 21:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0003_auto_20200623_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_carousel',
            name='url',
            field=models.CharField(default='http://www.nanxijy.com/', max_length=50, verbose_name='南西教育网课超链接'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='学校简介照片'),
        ),
        migrations.AlterField(
            model_name='about',
            name='preimg1',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='左边图片'),
        ),
        migrations.AlterField(
            model_name='about',
            name='preimg2',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='右边图片'),
        ),
        migrations.AlterField(
            model_name='accompanying',
            name='s_title',
            field=models.CharField(default='ACCOMPANYING EDUCATION', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='accompanying',
            name='title',
            field=models.CharField(default='陪伴式教育', max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='advertising1',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='advertising1',
            name='school',
            field=models.CharField(max_length=50, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='advertising2',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='choose_nancy',
            name='fifth2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='南西教育作为K12升学辅导培训的资深品牌，有数年的教育培训和应试辅导经验 已有数万名靴子升入理想学校的成功见证。', verbose_name='第五介绍'),
        ),
        migrations.AlterField(
            model_name='choose_nancy',
            name='first2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='南西教育作为K12升学辅导培训的资深品牌， 有数年的教育培训和应试辅导经验， 已有数万名学子升入理想学校的成功见证。', verbose_name='第一介绍'),
        ),
        migrations.AlterField(
            model_name='choose_nancy',
            name='fourth2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='教材由教研部数位经验丰富的教研大牛自主研发而成， 根据不同层次的学生学情，研发不同层次的教材，教学层次分明，实用性强', verbose_name='第四介绍'),
        ),
        migrations.AlterField(
            model_name='choose_nancy',
            name='second2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='每周进行学科教研活动，形成完整的教学设计方案，每月集中分析学生学习情况， 教研针对性辅导方案，每季度举行教师赛课，激励教师不断的提高教学质量。', verbose_name='第二介绍'),
        ),
        migrations.AlterField(
            model_name='choose_nancy',
            name='third2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='学校总部拥有完整的教师培训体系，新教师侧重教学技能的扎实 ，中级教师侧重教学方式的创新，高级教师侧重教研学术的研究。', verbose_name='第三介绍'),
        ),
        migrations.AlterField(
            model_name='choose_us',
            name='s_title',
            field=models.CharField(default='CHOOSE Us', max_length=20, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='age3',
            field=models.CharField(blank=True, default='6-8岁', max_length=20, verbose_name='年龄段'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='age4',
            field=models.CharField(blank=True, default='6-8岁', max_length=20, verbose_name='年龄段'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course3',
            field=models.CharField(blank=True, default='零基础入门首选让编程像搭积木一样好', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course3_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course4',
            field=models.CharField(blank=True, default='零基础入门首选让编程像搭积木一样好', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course4_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course_title3',
            field=models.CharField(blank=True, default='C++编程课', max_length=100, verbose_name='课程标题三'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='course_title4',
            field=models.CharField(blank=True, default='竞赛培训', max_length=100, verbose_name='课程标题四'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='inner3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='知识：理解计算机编程的基本概念，设计有趣的游戏和动画作品， 分析分解项目，完成从无到有的创作，规划研究管理小型项目。 能力:建立逻辑思维，树立解决问题意识，增加对学习的兴趣和信心，掌握编程基础知识', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='class_teach',
            name='inner4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='知识：理解计算机编程的基本概念，设计有趣的游戏和动画作品， 分析分解项目，完成从无到有的创作，规划研究管理小型项目。 能力:建立逻辑思维，树立解决问题意识，增加对学习的兴趣和信心，掌握编程基础知识', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='img',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='新闻图片'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='inner1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='知识：理解计算机编程的基本概念，设计有趣的游戏和动画作品， 分析分解项目，完成从无到有的创作，规划研究管理小型项目。 能力:建立逻辑思维，树立解决问题意识，增加对学习的兴趣和信心，掌握编程基础知识', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='inner2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='知识：理解计算机编程的基本概念，设计有趣的游戏和动画作品， 分析分解项目，完成从无到有的创作，规划研究管理小型项目。 能力:建立逻辑思维，树立解决问题意识，增加对学习的兴趣和信心，掌握编程基础知识', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match1',
            field=models.CharField(blank=True, default='SCRATCH', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match1_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match2',
            field=models.CharField(blank=True, default='PYTHON', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match2_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match3_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='first_match',
            name='match_title1',
            field=models.CharField(blank=True, default='全国青少年创意编程与智能设计大赛', max_length=100, verbose_name='比赛标题一'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='course1_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='course2_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='course3_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='nancy_teacher',
            name='s_title',
            field=models.CharField(default='PERSONS QUALIFIED TO TEACH', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='nancy_teacher',
            name='title',
            field=models.CharField(default='南西师资', max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='reading_life',
            name='course1_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是需要总监定稿1', max_length=100, verbose_name='介绍一'),
        ),
        migrations.AlterField(
            model_name='reading_life',
            name='course2_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是需要总监定稿2', max_length=100, verbose_name='介绍二'),
        ),
        migrations.AlterField(
            model_name='reading_life',
            name='course3_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是需要总监定稿3', max_length=100, verbose_name='介绍三'),
        ),
        migrations.AlterField(
            model_name='service',
            name='after_inner',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是课后的内容', verbose_name='课后内容'),
        ),
        migrations.AlterField(
            model_name='service',
            name='before_inner',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是课前的内容', verbose_name='课前内容'),
        ),
        migrations.AlterField(
            model_name='service',
            name='in_inner',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是课中的内容', verbose_name='课中内容'),
        ),
        migrations.AlterField(
            model_name='six_teach',
            name='s_title',
            field=models.CharField(default='SIX STEP TEACHING METHOD', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='teacher_select',
            name='s_title',
            field=models.CharField(default='TEACHER SELECTION', max_length=100, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='teacher_select',
            name='title',
            field=models.CharField(default='教师选拔', max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why1_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why2_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why3',
            field=models.CharField(blank=True, default='小南编程三大优势', max_length=100, verbose_name='第三'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why3_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why3_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='这是', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why4',
            field=models.CharField(blank=True, default='CSTA课程设计指标', max_length=100, verbose_name='第四'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why4_img',
            field=models.ImageField(blank=True, upload_to='programming', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='why_choose',
            name='why4_int',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='这是', verbose_name='介绍'),
        ),
    ]
