# Generated by Django 3.0.7 on 2020-07-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0006_auto_20200625_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default='邮箱: 12@qq.com', max_length=50, verbose_name='邮箱'),
        ),
    ]
