# Generated by Django 3.0.7 on 2020-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0007_auto_20200701_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='signature1',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='签名1'),
        ),
        migrations.AddField(
            model_name='about',
            name='signature2',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='签名2'),
        ),
    ]
