# Generated by Django 3.0.7 on 2020-08-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0008_auto_20200816_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_select',
            options={'verbose_name': '1首页-5教师选拔', 'verbose_name_plural': '1首页-5教师选拔'},
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name1',
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name2',
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name3',
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name4',
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name5',
        ),
        migrations.RemoveField(
            model_name='choose_us',
            name='choose_name6',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach10',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach12',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach2',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach4',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach6',
        ),
        migrations.RemoveField(
            model_name='six_teach',
            name='six_teach8',
        ),
        migrations.RemoveField(
            model_name='teacher_select',
            name='advertising1_img',
        ),
        migrations.RemoveField(
            model_name='teacher_select',
            name='advertising2_img',
        ),
        migrations.AddField(
            model_name='advertising1',
            name='advertising_img',
            field=models.ImageField(default=None, upload_to='advertising', verbose_name='点击咨询图片'),
        ),
        migrations.AddField(
            model_name='advertising1',
            name='img',
            field=models.ImageField(default=None, upload_to='choose_teach', verbose_name='广告栏图片'),
        ),
        migrations.AddField(
            model_name='advertising2',
            name='advertising_img',
            field=models.ImageField(default=None, upload_to='advertising', verbose_name='立即领取广告图片'),
        ),
        migrations.AddField(
            model_name='advertising2',
            name='img',
            field=models.ImageField(default=None, upload_to='choose_teach', verbose_name='广告栏图片'),
        ),
        migrations.AddField(
            model_name='teacher_select',
            name='img1',
            field=models.ImageField(default=None, upload_to='advertising', verbose_name='图片一'),
        ),
        migrations.AddField(
            model_name='teacher_select',
            name='img2',
            field=models.ImageField(default=None, upload_to='advertising', verbose_name='图片二'),
        ),
    ]
