# Generated by Django 3.0.7 on 2020-08-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0010_auto_20200822_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuangGao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='choose_teach', verbose_name='首页-广告栏图片')),
                ('advertising_img1', models.ImageField(blank=True, null=True, upload_to='advertising', verbose_name='点击咨询-背景图片')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='choose_teach', verbose_name='小南编程-广告栏图片')),
                ('advertising_img', models.ImageField(blank=True, null=True, upload_to='advertising', verbose_name='立即领取-背景图片')),
            ],
            options={
                'verbose_name': '广告栏图片-背景设置(立即咨询+点击领取)',
                'verbose_name_plural': '广告栏图片-背景设置(立即咨询+点击领取)',
            },
        ),
        migrations.RemoveField(
            model_name='advertising1',
            name='advertising_img',
        ),
        migrations.RemoveField(
            model_name='advertising1',
            name='img',
        ),
        migrations.RemoveField(
            model_name='advertising2',
            name='advertising_img',
        ),
        migrations.RemoveField(
            model_name='advertising2',
            name='img',
        ),
    ]
