# Generated by Django 3.0.7 on 2020-08-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0011_auto_20200822_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guanggao',
            old_name='advertising_img',
            new_name='advertising_img2',
        ),
    ]
