# Generated by Django 3.0.7 on 2020-09-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0012_auto_20200822_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='guanggao',
            name='zxdt_img',
            field=models.ImageField(blank=True, null=True, upload_to='advertising', verbose_name='最新动态右边广告'),
        ),
    ]
