# Generated by Django 3.0.7 on 2020-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0013_guanggao_zxdt_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_nav',
            name='other',
            field=models.CharField(blank=True, default='Copysdfght◎2020 AII rights sdfsdfs', max_length=100, null=True, verbose_name='备案号2'),
        ),
        migrations.AlterField(
            model_name='bt_nav',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='advertising', verbose_name='二维码'),
        ),
        migrations.AlterField(
            model_name='bt_nav',
            name='record1',
            field=models.CharField(blank=True, default='渝IC P备00000000号00', max_length=100, null=True, verbose_name='备案号1'),
        ),
        migrations.AlterField(
            model_name='bt_nav',
            name='record2',
            field=models.CharField(blank=True, default='渝公网安备00000000000000号', max_length=100, null=True, verbose_name='备案号2'),
        ),
        migrations.AlterField(
            model_name='bt_nav',
            name='url1',
            field=models.CharField(blank=True, default='#', max_length=100, null=True, verbose_name='备案号1链接'),
        ),
        migrations.AlterField(
            model_name='bt_nav',
            name='url2',
            field=models.CharField(blank=True, default='#', max_length=100, null=True, verbose_name='备案号2链接'),
        ),
    ]
